routes/web.php
<?php

use App\Http\Controllers\DashboardController;
use App\Http\Controllers\AdminController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\ClassController;
use App\Http\Controllers\SubjectController;
use App\Http\Controllers\ClassSubjectController;
use App\Http\Controllers\GradeController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\TeacherController;
use App\Http\Controllers\StudentController;
use App\Models\ClassSubjectModel;
use App\Models\Grade;
use Illuminate\Routing\RouteGroup;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\View;

// Route::get('/', function () {
//     return view('welcome');
// });


Route::get('/', [AuthController::class, 'login']);
Route::post('login', [AuthController::class, 'AuthLogin']);
Route::get('logout', [AuthController::class, 'logout']);
Route::get('forgot-password', [AuthController::class, 'forgotpassword']);
Route::post('forgot-password', [AuthController::class, 'PostForgotPassword']);
Route::get('reset/{token}', [AuthController::class, 'reset']);
Route::post('reset/{token}', [AuthController::class, 'PostReset']);

// Route::get('admin/dashboard', function () {
//     return view('admin.dashboard');
// })->name('admin.dashboard');



Route::group(['middleware' => 'admin'], function () {

    Route::get('/dashboard', function () {
        return view('admin.dashboard');
    })->name('admin.dashboard');

    Route::group(['prefix' => 'admin', 'as' => 'admin.'], function () {
        // Route::resource('grade', GradeController::class);
        Route::get('/dashboard', [DashboardController::class, 'dashboard']);
        Route::get('admin/list', [AdminController::class, 'list'])->name('admin.list');
        Route::get('admin/add', [AdminController::class, 'add']);
        Route::post('admin/add', [AdminController::class, 'insert']);
        Route::get('admin/edit/{id}', [AdminController::class, 'edit']);
        Route::post('admin/edit/{id}', [AdminController::class, 'update']);
        Route::get('admin/delete/{id}', [AdminController::class, 'delete']);



        //class
        Route::get('class/list', [ClassController::class, 'list']);
        Route::get('class/add', [ClassController::class, 'add']);
        Route::post('class/add', [ClassController::class, 'insert']);
        Route::get('class/edit/{id}', [ClassController::class, 'edit']);
        Route::post('class/edit/{id}', [ClassController::class, 'update']);
        Route::get('class/delete/{id}', [ClassController::class, 'delete']);

        //Subject
        Route::get('subject/list', [SubjectController::class, 'list']);
        Route::get('subject/add', [SubjectController::class, 'add']);
        Route::post('subject/add', [SubjectController::class, 'insert']);
        Route::get('subject/edit/{id}', [SubjectController::class, 'edit']);
        Route::post('subject/edit/{id}', [SubjectController::class, 'update']);
        Route::get('subject/delete/{id}', [SubjectController::class, 'delete']);


        ///assign_subject
        Route::get('assign_subject/list', [ClassSubjectController::class, 'list']);
        Route::get('assign_subject/add', [ClassSubjectController::class, 'add']);
        Route::post('assign_subject/add', [ClassSubjectController::class, 'insert']);
        Route::get('assign_subject/edit/{id}', [ClassSubjectController::class, 'edit']);
        Route::post('assign_subject/edit/{id}', [ClassSubjectController::class, 'update']);

        Route::get('assign_subject/edit_single/{id}', [ClassSubjectController::class, 'edit_single']);
        Route::post('assign_subject/edit_single/{id}', [ClassSubjectController::class, 'update_single']);
        Route::get('assign_subject/delete/{id}', [ClassSubjectController::class, 'delete']);


        //change_password
        Route::get('change_password', [UserController::class, 'change_password']);
        Route::post('change_password', [UserController::class, 'update_change_password']);

        //Student
        Route::get('student/list', [StudentController::class, 'list']);
        Route::get('student/add', [StudentController::class, 'add']);
        Route::post('student/add', [StudentController::class, 'insert']);



        //Teacher
        Route::get('teacher/list', [TeacherController::class, 'list']);
        Route::get('teacher/add', [TeacherController::class, 'add']);
        Route::post('teacher/add', [TeacherController::class, 'insert']);
        Route::get('teacher/edit/{id}', [TeacherController::class, 'edit']);
        Route::post('teacher/edit/{id}', [TeacherController::class, 'update']);
        Route::get('teacher/delete/{id}', [TeacherController::class, 'delete']);
        Route::get('teacher/detail/{id}', [TeacherController::class, 'detail']);

        // Grade
        Route::resource('grade', GradeController::class);

    });

});






Route::group(['middleware' => 'teacher'], function () {
    Route::get('teacher/dashboard', [DashboardController::class, 'dashboard']);

    Route::get('teacher/change_password', [UserController::class, 'change_password']);
    Route::post('teacher/change_password', [UserController::class, 'update_change_password']);
});

Route::group(['middleware' => 'student'], function () {
    Route::get('student/dashboard', [DashboardController::class, 'dashboard']);

    Route::get('student/change_password', [UserController::class, 'change_password']);
    Route::post('student/change_password', [UserController::class, 'update_change_password']);
});

Route::group(['middleware' => 'parent'], function () {
    Route::get('parent/dashboard', [DashboardController::class, 'dashboard']);

    Route::get('parent/change_password', [UserController::class, 'change_password']);
    Route::post('parent/change_password', [UserController::class, 'update_change_password']);
});

app/Models/Grade.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Grade extends Model
{
    use HasFactory;

    protected $fillable = [
        'name',
    ];

    public function classes () {
        return $this->hasMany(ClassRoom::class);
    }

}

app/Http/Controllers/GradeController.php
<?php

namespace App\Http\Controllers;

use App\Models\Grade;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;

use function Termwind\render;

class GradeController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $grades = Grade::paginate();

        return view('admin.grade.index', compact('grades'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        return view('admin.grade.partials._create');
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        // return $request->all();
        // dd($request->all());

        $validator = Validator::make($request->all(), [
            'name' => 'required',
        ]);

        if (!$validator->passes()) {
            return response()->json([
                'success' => false,
            ]);
        }

        Grade::create(['name' => $request->name]);

        $grades = Grade::paginate();

        $view = view('admin.grade.partials._table', compact('grades'))->render();

        return response()->json([
            'success' => true,
            'view' => $view,
            'data' => $request->all(),
        ]);
    }

    /**
     * Display the specified resource.
     */
    public function show(Grade $grade)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Grade $grade)
    {
        // $grade = Grade::findOrFail($id)
        // dd($grade);

        return view('admin.grade.partials._edit', compact('grade'));
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, Grade $grade)
    {
        $grade->name = $request->name;
        $grade->save();

        $grades = Grade::paginate();
        $view = view('admin.grade.partials._table', compact('grades'))->render();

        return response()->json([
            'view' => $view,
            'data' => $request->all(),
        ]);

    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Grade $grade)
    {
        $grade->delete();

        $grades = Grade::paginate();
        $view = view('admin.grade.partials._table', compact('grades'))->render();

        return response()->json([
            'view' => $view,
        ]);
    }
}

resources/views/admin/grade/partials/_create.blade.php
<div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title">{{ __('Add Grade') }}</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
            </button>
        </div>
        <form action="{{ route('admin.grade.store') }}" class="submit-form" method="post">
            <div class="modal-body">
                @csrf
                <div class="form-group">
                    <label for="name">{{ __('Name') }}</label>
                    <input type="number" name="name" min="1" class="form-control">
                </div>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">{{ __('Close') }}</button>
                <button type="submit" class="btn btn-primary submit">{{ __('Save') }}</button>
            </div>
        </form>
    </div>
</div>

<script>
    $('.submit').click(function (e) {
        e.preventDefault();
        var data = $('.submit-form').serialize();
        console.log(data);
        $.ajax({

            type: "post",
            url: `{{ route('admin.grade.store') }}`,
            data: data,
            // dataType: "json",
            success: function (response) {
                // console.log(response);
                if (response.success == false) {
                    alert('error');
                } else {
                    $('div.modal_form').modal('hide');
                    $('.table-wrapper').replaceWith(response.view);
                }

                $('.table-wrapper').replaceWith(response.view);
                const Toast = Swal.mixin({
                    toast: true,
                    position: 'top-right',
                    // iconColor: 'white',
                    customClass: {
                        popup: 'colored-toast'
                    },
                    showConfirmButton: false,
                    timer: 2000,
                    timerProgressBar: true
                });
                Toast.fire({
                    icon: 'success',
                    title: 'Success'
                });

            }
        });
    });
</script>

resources/views/admin/grade/partials/_edit.blade.php
<div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title">{{ __('Edit Grade') }}</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
            </button>
        </div>
        <form action="{{ route('admin.grade.update', $grade->id) }}" class="submit-form" method="post">
            <div class="modal-body">
                @csrf
                @method('PUT')
                <div class="form-group">
                    <label for="name">{{ __('Name') }}</label>
                    <input type="number" name="name" min="1" value="{{ $grade->name }}" class="form-control">
                </div>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">{{ __('Close') }}</button>
                <button type="submit" class="btn btn-primary submit">{{ __('Save') }}</button>
            </div>
        </form>
    </div>
</div>

<script>
    $('.submit').click(function (e) {
        e.preventDefault();
        var data = $('.submit-form').serialize();
        console.log(data);
        $.ajax({

            type: "post",
            url: `{{ route('admin.grade.update', $grade->id) }}`,
            data: data,
            // dataType: "json",
            success: function (response) {
                // console.log(response);
                $('div.modal_form').modal('hide');
                $('.table-wrapper').replaceWith(response.view);
                $('.table-wrapper').replaceWith(response.view);
                const Toast = Swal.mixin({
                    toast: true,
                    position: 'top-right',
                    // iconColor: 'white',
                    customClass: {
                        popup: 'colored-toast'
                    },
                    showConfirmButton: false,
                    timer: 2000,
                    timerProgressBar: true
                });
                Toast.fire({
                    icon: 'success',
                    title: 'Success'
                });
            }
        });
    });
</script>

resources/views/admin/grade/partials/_table.blade.php
<div class="card-body p-0 table-wrapper">
    <table class="table table-striped">
        <thead>
            <tr>
                <th >#</th>
                <th>Name</th>
                {{-- <th>Created by</th> --}}
                <th>Create date</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($grades as $grade)
                <tr>
                    <td>{{$grade->id}}</td>
                    <td>{{$grade->name}}</td>
                    <td>{{ $grade->created_at->format('d M Y h:i A') }}</td>
                    <td>
                        <a href="#" data-href="{{ route('admin.grade.edit', $grade->id) }}" data-container=".modal_form" class="btn btn-primary btn-sm btn-edit">{{ __('Edit') }}</a>

                        <form action="{{ route('admin.grade.destroy', $grade->id) }}" class="d-inline-block form-delete-{{ $grade->id }}">
                            @csrf
                            @method('DELETE')
                            <button type="submit" data-id="{{ $grade->id }}" data-href="{{ route('admin.grade.destroy', $grade->id) }}" class="btn btn-danger btn-sm btn-delete">{{ __('Delete') }}</button>
                        </form>
                    </td>
                </tr>
            @endforeach
        </tbody>
    </table>
    <div style="padding: 10px; float: right;">
        {{-- {!! $getRecord->appends(Illuminate\Support\Facades\Request::except('page'))->links()!!} --}}
        {{ $grades->links() }}
    </div>
</div>